### ISSUE TITLE
OS boots as Read Only

### ISSUE THREAD

**Issue by mathewlear** [IceWhaleTech/zimaos-rauc#1]
How to boot with OS drive as R/W ?

**Comment by jerrykuku** [comment]
ZimaOS is a custom system, and in order to provide more stable OTA functionality, only a very few directories other than the /DATA directory are writable.

**Comment by Lauren-ED209** [comment]
> How to boot with OS drive as R/W ?

Could you please introduce more details about your scenarios requirements?

**Comment by silycr** [comment]
> > How to boot with OS drive as R/W ?
> 
> Could you please introduce more details about your scenarios requirements?

Mounting nfs on boot through /etc/fstab ?

**Comment by Lauren-ED209** [comment]
Considering that this requirement has already been mentioned in the following link, we are closing this issue.
https://github.com/IceWhaleTech/zimaos-rauc/issues/2

**Comment by plangin** [comment]
> > How to boot with OS drive as R/W ?
> 
> Could you please introduce more details about your scenarios requirements?

- change root password (for SSH)
- change hostname
- set static IP address
