### ISSUE TITLE
系统关机在N6005NAS上的异常

### ISSUE THREAD

**Issue by A13788899580** [IceWhaleTech/zimaos-rauc#31]
在系统上进行关机，NAS就直接断电了，系统没有正常退出程序，而如果在NAS上进行物理关机，则系统正常退出。

**Comment by CorrectRoadH** [comment]
是指在前端点关机吗? 然后直接断电是指电源灯啥的，很快(1、2秒内)就灭吗?🤔
然后系统没有正常退出程序是指哪些。比如你开了什么应用，然后什么数据没有被保存
然后物理关机是指按主机箱上的电源键吗? 正常退出的行为是指哪些👀

**Comment by A13788899580** [comment]
通过监控屏，我可以看到：
如果是按物理按键关机，ZimaOS会退出相应进程（就如其他Linux发行版那样），这里会有不到10秒的时间（具体没计算），完全退出后，然后NAS断电，电源灯熄灭；
如果是点击ZimaOS内的关机，直接就是电源的熄灭，当然监控屏也熄灭了，我的理解是没有对任何进程进行处理，就给了指令断电了；
我用的是畅网6005的板子。
暂时没有发现数据没被保存的问题。

**Comment by LinkLeong** [comment]
感谢你的反馈,我在查询资料后发现了问题,golang的关机确实是直接断电效率更高,但不是关闭服务后关机.已经确认修改为 `shutdown -h now`,同样的重启也是一样.再次感谢你的反馈
