### ISSUE TITLE
SCSI Drives in proxmox do not work, SATA drives do.

### ISSUE THREAD

**Issue by corcorac** [IceWhaleTech/zimaos-rauc#36]
Drives added in GUI as scsi# (scsi1, 2, 3, etc) or passed through as scsi# type will show as "Unhealthy" no matter what settings are chosen. Passed through as sata# (sata1, 2, etc) will show healthy, show temp readout, and allow for raid/creating storage pools, etc.

In a Proxmox VM, using steps in documentation linked on main Github page, both before and after expanding the original image. I can provide any logs/info needed to help.

---

Images of scsi1 in ZimaOS, drive marked unhealthy:

Proxmox settings qcow:
<img width="606" alt="ZimaOS SCSI-QEMU SSD" src="https://github.com/IceWhaleTech/zimaos-rauc/assets/20197102/59e4ffb2-e77e-4022-b463-6933c07f2622">

Proxmox settings raw:
<img width="604" alt="ZimaOS SCSI-raw SSD" src="https://github.com/IceWhaleTech/zimaos-rauc/assets/20197102/40dc5dc1-827f-41fe-b4fa-2086077789c3">

ZimaOS:
<img width="292" alt="ZimaOS Status" src="https://github.com/IceWhaleTech/zimaos-rauc/assets/20197102/6b35d7d3-2b31-4b38-98aa-ac04cfdf55f1">

<img width="691" alt="ZimaOS Storage Status" src="https://github.com/IceWhaleTech/zimaos-rauc/assets/20197102/085f863c-67fc-471f-ae74-17ba0279f5d5">

---

Images of scsi1 working correctly in CasaOS minus drive temp:

Proxmox settings:
<img width="606" alt="CasaOS SCSI SSD" src="https://github.com/IceWhaleTech/zimaos-rauc/assets/20197102/6f79ddc6-1058-4767-bc8f-9ea00b191ea8">

CasaOS:
<img width="617" alt="CasaOS Status" src="https://github.com/IceWhaleTech/zimaos-rauc/assets/20197102/c22338a2-7585-4fdc-8be0-8bb0827aeae0">

<img width="619" alt="CasaOS Storage Status" src="https://github.com/IceWhaleTech/zimaos-rauc/assets/20197102/e8a1f10c-bd67-4107-a746-c3b94e52052e">

**Comment by LinkLeong** [comment]
Can you run the command with the path test1 and see what the return message is?
smartctl -a -n standby ${path} -j

**Comment by LinkLeong** [comment]
![image](https://github.com/IceWhaleTech/zimaos-rauc/assets/13556972/5fcb8c67-01e7-4eed-b86c-9dc2c80254ea)
I checked, and it says unsupported here. I've made a judgment call, and if it's not supported, it's considered healthy.

**Comment by corcorac** [comment]
Sorry about that, I was asleep at the time.
I can still run it on my end if need be? I imagine it's the same and smart info isn't passing through the scsi driver, but is with sata. Thank you on the judgment call, that works for me since proxmox does still monitor smart on the disks.

May be worth it to still warn "healthy, no smart support" on hover as some may not know to ensure they're checking smart outside of the VM, but not exactly imperative either.

**Comment by LinkLeong** [comment]
I have dealt with this issue and still consider it healthy without a clear judgment of failure. Thanks for your feedback. I'll close the file and reopen it if in doubt.
