### ISSUE TITLE
挂载新硬盘失败后，一直提示有新硬盘

### ISSUE THREAD

**Issue by A13788899580** [IceWhaleTech/zimaos-rauc#38]
需要帮助
1. 插入新硬盘后，发现新硬盘，进行格式化并启用，出现提示：**mke2fs 1.46.5 (30-Dec-2021) mkfs.ext4: No medium found while trying to determine filesystem size .**。
2. 拔掉硬盘后，还是一直显示有一块新硬盘，重启一直存在，插入硬盘后，操作格式化，任然出现上面的提示**mke2fs 1.46.5 (30-Dec-2021) mkfs.ext4: No medium found while trying to determine filesystem size .**。
3. 进入ssh，lsblk可以看到有sdb(sda已有挂载正常的硬盘），Fdisk无法看到/dev/sdb。
以上需要如果解决，怎么去掉系统一直提示“有一块新硬盘”，或者是怎么干掉sdb，我尝试了一些命令都无法删除。

**Comment by LinkLeong** [comment]
你可以先查看一下sdb的磁盘是否健康smartctl -H /dev/sdb
我这边进行了复现,未能出现你说的情况.如果条件允许的话你可以录个屏,方便我们分析问题.感谢你的反馈.

**Comment by A13788899580** [comment]
这个问题让我换了机器，后面等新机子后看看是否还有同样的问题
