### ISSUE TITLE
Can not boot from NVMe drive

### ISSUE THREAD

**Issue by plangin** [IceWhaleTech/zimaos-rauc#46]
I tried to install the 1.0.0 open beta onto an NVMe drive.

The installer did recognize the device /dev/nvme0n1 and installation went fine.

But after reboot I had no success, ZimaOS won't boot. It is also not visible in the UEFI boot menu.

**Comment by plangin** [comment]
Tried again with the 1.1.0 Open Beta installier.

This time I installed ZimaOS on both drives NVMe and SATA (/dev/nvme0n1 and /dev/sda).

UEFI Boot manager does not recognize both of them. So it is not directly a NVMe issue.

Other OS like Arch Linux run fine on the same machine, btw.

**Comment by plangin** [comment]
> UEFI Boot manager does not recognize both of them. So it is not directly a NVMe issue.

OK, to be more exact:

The entry in my UEFI boot manager ist called: GRUB (Drive not present).

I mounted the drives, all 8 partitions are there including boot and the bootx64.efi file.
So installation works fine, but something with the GRUB install goes wrong I assume.

**Comment by plangin** [comment]
In the meantime, I restored 1.1.0 beta on both NVMe and SATA using balenaEtcher. This is how the drives look afterwards:

![nvme](https://github.com/IceWhaleTech/zimaos-rauc/assets/3201804/89cca763-8a5c-44d1-b13b-ef00905a3c64)

![sata](https://github.com/IceWhaleTech/zimaos-rauc/assets/3201804/7d86b245-2de4-4fdc-90d3-06ce55e9ad8e)


Nevertheless, none of the drive is booting. Seems to be some additional grub.cfg issue. Will create another issue, if necessary.

**Comment by Plastermaster** [comment]
I'm wondering if this could possibly be related to the issue I have https://github.com/IceWhaleTech/zimaos-rauc/issues/61#issue-2274129441

**Comment by plangin** [comment]
Installing 1.2.x works fine onto the NVMe drive.
So I can close this issue.

Nevertheless., the 8th partition is still too small and the whole drive is not used at all.
Will create another issue for that if not done yet by someone else.

**Comment by plangin** [comment]
Expanding of 8th partition does also work fine now. Tested with v1.3.1
