### ISSUE TITLE
关于最新1.1版本升级的问题

### ISSUE THREAD

**Issue by A13788899580** [IceWhaleTech/zimaos-rauc#55]
有最新的版本1.1了，我看到的提醒是文件很大需要从分享的链接直接下载。
我现在的版本是1.0，没有看到升级提示，那是否就是需要下载安装包，然后重新安装？
如果重新安装，会不会对原有安装的容器和文件有影响？

**Comment by CorrectRoadH** [comment]
测试同学说已经在社区中回复你了。那我这里就把issue给关了
