### ISSUE TITLE
Failed to load apps

### ISSUE THREAD

**Issue by answer35** [IceWhaleTech/zimaos-rauc#59]
Hi,

I recently installed ZimaOS on a SSD using a fedora live usb to use balenaetcher as suggested in the wiki.
Then I am able to boot ZimaOS and connect to its webUI but apps are failing to start and it loop on that. On the screen connected to my computer, I have no message at all.

I will try to redo the installation process in case anything went wrong but balena did successfully complete the flash so if anyone knows what happens, here you can help someone :)

**Comment by answer35** [comment]
Using v1.0.0 make it works. I guess I have an issue with 1.1.0

**Comment by aab44** [comment]
It appears that my docker service wasnt started. I ran the following command and my system is back up:

sudo systemctl start docker.service
