### ISSUE TITLE
zimaos v1.2.0-beta1 无法上传文件

### ISSUE THREAD

**Issue by M6ZeroG** [IceWhaleTech/zimaos-rauc#62]
1、安装情况：
- 使用VMware® Workstation 16 Pro安装
- 使用StarWind V2V Converter转换zimaos_zimacube-1.2.0-beta1_installer.img为vmdk后作为NVMe虚拟硬盘挂载到需虚拟机，通过设置从此硬盘启动安装
- 虚拟机配置：内存4G、处理器4、虚拟硬盘1：NVMe 50G（系统盘）、虚拟硬盘2：SATA 20G（存储盘）、虚拟硬盘3：SATA 20G（存储盘）、网络适配器 NAT、固件类型UEFI

2、故障1：刚启动zimaos后进入web界面反复提示Failed to load apps,please refresh later.无法加载APP， 如图
![Failed to load apps](https://github.com/IceWhaleTech/zimaos-rauc/assets/22573120/e32c57e4-7da9-447b-a3ff-fc0327f7f9de)

3、故障2：约1-2分钟后不再提示Failed to load apps,please refresh later，APP完成加载，Files中无法上传文件，可以新建文件和文件夹，如图
![FilesUpload](https://github.com/IceWhaleTech/zimaos-rauc/assets/22573120/04b31e1f-d55c-4b1f-b1c4-ecdc01c6ca96)

盼复，为感！

**Comment by Marrrrrrrrry** [comment]
我vm17 其他均为同环境，未复现该问题

**Comment by M6ZeroG** [comment]
zimaos_zimacube-1.2.0-beta2后此问题已修复
