### ISSUE TITLE
CPU/RAM expanded view not rendering properly

### ISSUE THREAD

**Issue by trapexit** [IceWhaleTech/zimaos-rauc#7]
Running on a ZimaBoard 832. 0.4.8 flashed to internal storage and then updated to 0.4.9 via OTA.

![image](https://github.com/IceWhaleTech/zimaos-rauc/assets/197676/9e118b47-f78a-4589-a795-a383bfa670b1)

![image](https://github.com/IceWhaleTech/zimaos-rauc/assets/197676/6d7eb66c-db45-4e32-ab1d-9a0af0e233a3)

**Comment by Lauren-ED209** [comment]
Just confirming with you, are you running any Docker applications?

**Comment by trapexit** [comment]
At the time I had nothing setup yet. But those lines on the sides still appear when you do.

**Comment by Lauren-ED209** [comment]
Okay, I understand the issue now. Will check with the front-end team tomorrow. Thanks.

**Comment by trapexit** [comment]
It happens due to a "Dark Reader" browser plugin.
