### ISSUE TITLE
[bug report] ZVM 内文件管理器路径对应错误(?)文件管理器刷新不及时

### ISSUE THREAD

**Issue by Marrrrrrrrry** [IceWhaleTech/zimaos-rauc#73]
环境：zima os v1.2.1
在 zvm 选择镜像时，发现点击上半部收藏中的所有文件夹，右侧均不会刷新，是100% 复现的恶性 bug

![ZIMA](https://github.com/IceWhaleTech/zimaos-rauc/assets/34876935/3d3e0c4d-58db-49e4-ba5f-34fe05d292a5)

**Comment by LinkLeong** [comment]
v1.2.2已解决该问题，请等待升级。
