### ISSUE TITLE
[bug report] zima 中多处对同一路径描述不一致

### ISSUE THREAD

**Issue by Marrrrrrrrry** [IceWhaleTech/zimaos-rauc#77]
zvm 内的文件管理器对根目录描述不一致。而且二者并非等价或软连接，尝试手工修改发现不能替换使用

![z1](https://github.com/IceWhaleTech/zimaos-rauc/assets/34876935/cd04293d-a502-42f5-aa2a-d7e27d741f7c)
![z2](https://github.com/IceWhaleTech/zimaos-rauc/assets/34876935/619064a5-4ac4-4592-8325-eb71338d8d39)
![z3](https://github.com/IceWhaleTech/zimaos-rauc/assets/34876935/c57dc7d4-3000-4d27-8e92-ebe8fbcf6f78)

**Comment by Marrrrrrrrry** [comment]
但这版本的 zima 好像更偏好 ZimaOS-HD 根目录挂载出去都是 \\10.x.x.x\ZimaOS-HD
浏览器路径也为 ZimaOS-HD
![image](https://github.com/IceWhaleTech/zimaos-rauc/assets/34876935/5ff54199-046b-43f3-b5fc-f7fa2e5aaa7a)

**Comment by LinkLeong** [comment]
我们也意识到了多出路径表现不一致的问题，会在后续版本陆续修复，zvm的路径会在v1.2.2版本中修复。
